# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerStandardization
                                 A QGIS plugin
 This plugin standardize the layer columns and row id before it is used for map2loop
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-13
        copyright            : (C) 2022 by Michel Nzikou
        email                : michel.nzikou@alumni.uleth.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerStandardization class from file LayerStandardization.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_standardization import LayerStandardization
    return LayerStandardization(iface)
